/**
 * The fix for data generated by an older version of the app, for inline use
 * in "…to <do something>" hints: import Timeline.json again (in the browser,
 * from the page footer) or re-run the command-line preprocess.
 */
const CODE = 'bg-gray-800 text-orange-400 px-1.5 py-0.5 rounded';

export default function RegenerateHint() {
  return (
    <>
      Import your <code className={CODE}>Timeline.json</code> again (page footer) or re-run{' '}
      <code className={CODE}>npm run preprocess</code>
    </>
  );
}
