/**
 * TypeScript types for all data shapes the frontend reads.
 *
 * The generated datasets' types are defined once, by the pipeline that
 * produces them (src/pipeline/types.ts, shared by the CLI and the in-browser
 * import), and re-exported here, so there is nothing to keep in sync by
 * hand. Shapes derived client-side for the selected time range live in
 * aggregate.ts.
 *
 * Dates are 'YYYY-MM-DD' local calendar dates and timestamps are ISO strings
 * in the local UTC offset where things happened; see src/pipeline/types.ts.
 */

import type { FeatureCollection, MultiPolygon, Polygon } from 'geojson';

export type {
  Datasets,
  DatasetKey,
  FamilyHome,
  Flight,
  GeographyData,
  HomePeriod,
  MatchedAirport,
  NightEntry,
  RouteSegment,
  Stats,
  Trip,
  TripPlace,
  Visit,
} from './pipeline/types';

/**
 * Feature properties of public/world-countries.geo.json — a vendored,
 * simplified Natural Earth admin-0 file (not generated by the pipeline,
 * which only reads its names to attach ISO codes).
 */
export interface WorldCountryProperties {
  iso3: string;
  name: string;
  /** Alternative names, used by the pipeline for matching */
  names: string[];
}

export type WorldCountries = FeatureCollection<Polygon | MultiPolygon, WorldCountryProperties>;
